import { Product } from './product';

export const PRODUCTDATA: Product[] = [{
"id" : 1,
"name" : "Nike Roshe Run Pre-miun Holiday",
"brandicon" : "/images/icons/nike-icon.png",
"description" : "This is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.",
"fulldescription" : "With its beautiful premium leather, lace-up oxford styling, recycled rubber outsoles and 9-inch height, this Earthkeepers City Premium style is an undeniably handsome boot. To complement its rustic, commanding outer appearance, we've paid attention to the inside as well - by adding SmartWool® faux shearling to the linings and crafting the footbed using our exclusive anti-fatigue comfort foam technology to absorb shock.",
"details" : ["Premium burnished full-grain leather and suede upper", "Leather is from a tannery rated Silver for its water, energy and waste-management practices", "Leather lining and footbed for a premium feel and optimal comfort", "SmartWool® faux shearling lining is made with 60% merino wool and 40% PET", "Reflective insole board for additional warmth under foot", "100% organic cotton laces", "SmartWool® fabric-lined anti-fatigue footbed provides superior, all-day comfort and climate control", "Timberland® exclusive Gripstick™ and Green Rubber™ outsole is made with 42% recycled rubber"],
"price" : 109,
"saleprice" : 174,
"availablesizes" : [37, 38, 39, 40],
"reviews" : 8,
"images" : ["/images/shoe1.jpg", "/images/shoe2.jpg", "/images/shoe3.jpg"],
"category" : "Men's Footwear"
},
{
"id" : 2,
"name" : "Nike Roshe Run Pre-miun Holiday",
"brandicon" : "/images/icons/nike-icon.png",
"description" : "This is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.",
"fulldescription" : "With its beautiful premium leather, lace-up oxford styling, recycled rubber outsoles and 9-inch height, this Earthkeepers City Premium style is an undeniably handsome boot. To complement its rustic, commanding outer appearance, we've paid attention to the inside as well - by adding SmartWool® faux shearling to the linings and crafting the footbed using our exclusive anti-fatigue comfort foam technology to absorb shock.",
"details" : ["Premium burnished full-grain leather and suede upper", "Leather is from a tannery rated Silver for its water, energy and waste-management practices", "Leather lining and footbed for a premium feel and optimal comfort", "SmartWool® faux shearling lining is made with 60% merino wool and 40% PET", "Reflective insole board for additional warmth under foot", "100% organic cotton laces", "SmartWool® fabric-lined anti-fatigue footbed provides superior, all-day comfort and climate control", "Timberland® exclusive Gripstick™ and Green Rubber™ outsole is made with 42% recycled rubber"],
"price" : 109,
"saleprice" : 174,
"availablesizes" : [37, 38, 39, 40],
"reviews" : 8,
"images" : ["/images/shoe1.jpg", "/images/shoe2.jpg", "/images/shoe3.jpg"],
"category" : "Women's Footwear"
},
{
"id" : 3,
"name" : "Nike Roshe Run Pre-miun Holiday",
"brandicon" : "/images/icons/nike-icon.png",
"description" : "This is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.",
"fulldescription" : "With its beautiful premium leather, lace-up oxford styling, recycled rubber outsoles and 9-inch height, this Earthkeepers City Premium style is an undeniably handsome boot. To complement its rustic, commanding outer appearance, we've paid attention to the inside as well - by adding SmartWool® faux shearling to the linings and crafting the footbed using our exclusive anti-fatigue comfort foam technology to absorb shock.",
"details" : ["Premium burnished full-grain leather and suede upper", "Leather is from a tannery rated Silver for its water, energy and waste-management practices", "Leather lining and footbed for a premium feel and optimal comfort", "SmartWool® faux shearling lining is made with 60% merino wool and 40% PET", "Reflective insole board for additional warmth under foot", "100% organic cotton laces", "SmartWool® fabric-lined anti-fatigue footbed provides superior, all-day comfort and climate control", "Timberland® exclusive Gripstick™ and Green Rubber™ outsole is made with 42% recycled rubber"],
"price" : 109,
"saleprice" : 174,
"availablesizes" : [37, 38, 39, 40],
"reviews" : 8,
"images" : ["/images/shoe1.jpg", "/images/shoe2.jpg", "/images/shoe3.jpg"],
"category" : "Kids's Footwear"
},
{
"id" : 4,
"name" : "Nike Roshe Run Pre-miun Holiday",
"brandicon" : "/images/icons/nike-icon.png",
"description" : "This is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.",
"fulldescription" : "With its beautiful premium leather, lace-up oxford styling, recycled rubber outsoles and 9-inch height, this Earthkeepers City Premium style is an undeniably handsome boot. To complement its rustic, commanding outer appearance, we've paid attention to the inside as well - by adding SmartWool® faux shearling to the linings and crafting the footbed using our exclusive anti-fatigue comfort foam technology to absorb shock.",
"details" : ["Premium burnished full-grain leather and suede upper", "Leather is from a tannery rated Silver for its water, energy and waste-management practices", "Leather lining and footbed for a premium feel and optimal comfort", "SmartWool® faux shearling lining is made with 60% merino wool and 40% PET", "Reflective insole board for additional warmth under foot", "100% organic cotton laces", "SmartWool® fabric-lined anti-fatigue footbed provides superior, all-day comfort and climate control", "Timberland® exclusive Gripstick™ and Green Rubber™ outsole is made with 42% recycled rubber"],
"price" : 109,
"saleprice" : 174,
"availablesizes" : [37, 38, 39, 40],
"reviews" : 8,
"images" : ["/images/shoe1.jpg", "/images/shoe2.jpg", "/images/shoe3.jpg"],
"category" : "Men's Footwear"
},
{
"id" : 5,
"name" : "Nike Roshe Run Pre-miun Holiday",
"brandicon" : "/images/icons/nike-icon.png",
"description" : "This is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.",
"fulldescription" : "With its beautiful premium leather, lace-up oxford styling, recycled rubber outsoles and 9-inch height, this Earthkeepers City Premium style is an undeniably handsome boot. To complement its rustic, commanding outer appearance, we've paid attention to the inside as well - by adding SmartWool® faux shearling to the linings and crafting the footbed using our exclusive anti-fatigue comfort foam technology to absorb shock.",
"details" : ["Premium burnished full-grain leather and suede upper", "Leather is from a tannery rated Silver for its water, energy and waste-management practices", "Leather lining and footbed for a premium feel and optimal comfort", "SmartWool® faux shearling lining is made with 60% merino wool and 40% PET", "Reflective insole board for additional warmth under foot", "100% organic cotton laces", "SmartWool® fabric-lined anti-fatigue footbed provides superior, all-day comfort and climate control", "Timberland® exclusive Gripstick™ and Green Rubber™ outsole is made with 42% recycled rubber"],
"price" : 109,
"saleprice" : 174,
"availablesizes" : [37, 38, 39, 40],
"reviews" : 8,
"images" : ["/images/shoe1.jpg", "/images/shoe2.jpg", "/images/shoe3.jpg"],
"category" : "Women's Footwear"
},
{
"id" : 6,
"name" : "Nike Roshe Run Pre-miun Holiday",
"brandicon" : "/images/icons/nike-icon.png",
"description" : "This is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.",
"fulldescription" : "With its beautiful premium leather, lace-up oxford styling, recycled rubber outsoles and 9-inch height, this Earthkeepers City Premium style is an undeniably handsome boot. To complement its rustic, commanding outer appearance, we've paid attention to the inside as well - by adding SmartWool® faux shearling to the linings and crafting the footbed using our exclusive anti-fatigue comfort foam technology to absorb shock.",
"details" : ["Premium burnished full-grain leather and suede upper", "Leather is from a tannery rated Silver for its water, energy and waste-management practices", "Leather lining and footbed for a premium feel and optimal comfort", "SmartWool® faux shearling lining is made with 60% merino wool and 40% PET", "Reflective insole board for additional warmth under foot", "100% organic cotton laces", "SmartWool® fabric-lined anti-fatigue footbed provides superior, all-day comfort and climate control", "Timberland® exclusive Gripstick™ and Green Rubber™ outsole is made with 42% recycled rubber"],
"price" : 109,
"saleprice" : 174,
"availablesizes" : [37, 38, 39, 40],
"reviews" : 8,
"images" : ["/images/shoe1.jpg", "/images/shoe2.jpg", "/images/shoe3.jpg"],
"category" : "Kids's Footwear"
},
{
"id" : 7,
"name" : "Nike Roshe Run Pre-miun Holiday",
"brandicon" : "/images/icons/nike-icon.png",
"description" : "This is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.",
"fulldescription" : "With its beautiful premium leather, lace-up oxford styling, recycled rubber outsoles and 9-inch height, this Earthkeepers City Premium style is an undeniably handsome boot. To complement its rustic, commanding outer appearance, we've paid attention to the inside as well - by adding SmartWool® faux shearling to the linings and crafting the footbed using our exclusive anti-fatigue comfort foam technology to absorb shock.",
"details" : ["Premium burnished full-grain leather and suede upper", "Leather is from a tannery rated Silver for its water, energy and waste-management practices", "Leather lining and footbed for a premium feel and optimal comfort", "SmartWool® faux shearling lining is made with 60% merino wool and 40% PET", "Reflective insole board for additional warmth under foot", "100% organic cotton laces", "SmartWool® fabric-lined anti-fatigue footbed provides superior, all-day comfort and climate control", "Timberland® exclusive Gripstick™ and Green Rubber™ outsole is made with 42% recycled rubber"],
"price" : 109,
"saleprice" : 174,
"availablesizes" : [37, 38, 39, 40],
"reviews" : 8,
"images" : ["/images/shoe1.jpg", "/images/shoe2.jpg", "/images/shoe3.jpg"],
"category" : "Men's Footwear"
},
{
"id" : 8,
"name" : "Nike Roshe Run Pre-miun Holiday",
"brandicon" : "/images/icons/nike-icon.png",
"description" : "This is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.",
"fulldescription" : "With its beautiful premium leather, lace-up oxford styling, recycled rubber outsoles and 9-inch height, this Earthkeepers City Premium style is an undeniably handsome boot. To complement its rustic, commanding outer appearance, we've paid attention to the inside as well - by adding SmartWool® faux shearling to the linings and crafting the footbed using our exclusive anti-fatigue comfort foam technology to absorb shock.",
"details" : ["Premium burnished full-grain leather and suede upper", "Leather is from a tannery rated Silver for its water, energy and waste-management practices", "Leather lining and footbed for a premium feel and optimal comfort", "SmartWool® faux shearling lining is made with 60% merino wool and 40% PET", "Reflective insole board for additional warmth under foot", "100% organic cotton laces", "SmartWool® fabric-lined anti-fatigue footbed provides superior, all-day comfort and climate control", "Timberland® exclusive Gripstick™ and Green Rubber™ outsole is made with 42% recycled rubber"],
"price" : 109,
"saleprice" : 174,
"availablesizes" : [37, 38, 39, 40],
"reviews" : 8,
"images" : ["/images/shoe1.jpg", "/images/shoe2.jpg", "/images/shoe3.jpg"],
"category" : "Men's Footwear"
}]